"""Chunked hmmsearch for the HMMER rescue step (issue #31).

hmmsearch iterates profiles serially, and its cost is
(profiles x sequences). Measured on the 5sp v2 run: 14,949 profiles x
39,729 unplaced sequences = 5.8 h on 8 cores. The 15sp panel is 3.3-4.1x
larger on both axes, so the same step extrapolates to 2.7-4.1 DAYS against
a 3-day SLURM limit — and hmmsearch has no internal checkpoint. Splitting
the profile file makes the wall clock linear in the number of tasks while
conserving total work; profiles are independent, so the merged result is
identical to a single run (order differs; the parser sorts by best score).

Two deliberate design points:

- **SLURM is optional.** The generated runner detects `sbatch` and submits
  an array with `--wait` when it exists, otherwise runs the chunks in a
  bounded local background pool. The same script works on a laptop.
- **A truncated chunk must fail loudly.** HMMER terminates a `--tblout`
  file with `# [ok]`; `merge_tblouts` requires that marker in every chunk.
  Without the check, a killed task would silently yield a partial rescue
  that looks like a complete one.
"""

import logging
import shlex
import stat
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger("family_finder")

HMMER_OK_MARKER = "# [ok]"
CHUNK_GLOB = "chunk_*.tblout"
DOM_CHUNK_GLOB = "chunk_*.domtblout"


def split_hmm_file(hmm_path: Path, out_dir: Path, chunk_size: int) -> List[Path]:
    """Split a multi-profile HMM file into chunks of `chunk_size` profiles.

    Records are delimited by a lone `//` line; a chunk boundary is only ever
    placed after one, so no profile is ever cut in half.
    """
    if chunk_size <= 0:
        raise ValueError(f"chunk_size must be positive, got {chunk_size}")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    chunks: List[Path] = []
    buf: List[str] = []
    n_in_chunk = 0

    def flush():
        nonlocal buf, n_in_chunk
        if not buf:
            return
        path = out_dir / f"chunk_{len(chunks):04d}.hmm"
        path.write_text("".join(buf))
        chunks.append(path)
        buf, n_in_chunk = [], 0

    with open(hmm_path) as f:
        for line in f:
            buf.append(line)
            if line.rstrip("\n") == "//":
                n_in_chunk += 1
                if n_in_chunk >= chunk_size:
                    flush()
    flush()

    if not chunks:
        raise ValueError(f"No HMM profiles found in {hmm_path}")
    logger.info(f"Split {hmm_path.name} -> {len(chunks)} chunks "
                f"of <= {chunk_size} profiles in {out_dir}")
    return chunks


_RUNNER_TEMPLATE = """\
#!/bin/bash
# Generated by family_finder (issue #31): run hmmsearch over profile chunks.
# Works with or without SLURM — see the branch below.
set -euo pipefail

CHUNK_DIR={chunk_dir}
QUERY={query}
OUT_DIR={out_dir}
HMMSEARCH={hmmsearch}
THREADS={threads}
EVALUE={evalue}
N_CHUNKS={n_chunks}
MAX_CONCURRENT={max_concurrent}

mkdir -p "$OUT_DIR"

run_one() {{
  local i
  i=$(printf '%04d' "$1")
  "$HMMSEARCH" --tblout "$OUT_DIR/chunk_$i.tblout" \\
    --domtblout "$OUT_DIR/chunk_$i.domtblout" --noali \\
      -E "$EVALUE" --cpu "$THREADS" \\
      "$CHUNK_DIR/chunk_$i.hmm" "$QUERY" > /dev/null
}}

if [ "${{1:-}}" = "--one" ]; then      # array-task entry point
  run_one "$2"
  exit 0
fi

if command -v sbatch > /dev/null 2>&1; then
  echo "SLURM detected: submitting array of $N_CHUNKS tasks" >&2
  # --wait blocks until the whole array finishes, so the caller stays
  # synchronous exactly as the single-run path was.
  sbatch --wait \\
      --array=0-$((N_CHUNKS - 1))%"$MAX_CONCURRENT" \\
      --cpus-per-task="$THREADS" \\
      {sbatch_extra}\\
      --job-name=ff_hmmsearch \\
      --output="$OUT_DIR/slurm-%A_%a.out" \\
      --wrap="'$0' --one \\$SLURM_ARRAY_TASK_ID"
else
  echo "No SLURM: running $N_CHUNKS chunks locally, $MAX_CONCURRENT at a time" >&2
  pids=()
  for i in $(seq 0 $((N_CHUNKS - 1))); do
    run_one "$i" &
    pids+=($!)
    if [ "${{#pids[@]}}" -ge "$MAX_CONCURRENT" ]; then
      wait "${{pids[0]}}"
      pids=("${{pids[@]:1}}")
    fi
  done
  wait
fi
echo "all chunks finished" >&2
"""


def write_runner_script(
    path: Path,
    n_chunks: int,
    chunk_dir: Path,
    query_fasta: Path,
    out_dir: Path,
    hmmsearch_bin: str,
    threads: int,
    evalue: float,
    max_concurrent: int = 10,
    sbatch_extra: str = "",
) -> Path:
    """Write the executable chunk runner (SLURM-optional)."""
    path = Path(path)
    path.write_text(_RUNNER_TEMPLATE.format(
        chunk_dir=shlex.quote(str(chunk_dir)),
        query=shlex.quote(str(query_fasta)),
        out_dir=shlex.quote(str(out_dir)),
        hmmsearch=shlex.quote(str(hmmsearch_bin)),
        threads=threads,
        evalue=evalue,
        n_chunks=n_chunks,
        max_concurrent=max_concurrent,
        sbatch_extra=(sbatch_extra + " \\\n      ") if sbatch_extra else "",
    ))
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return path


def merge_tblouts(tblout_dir: Path, out_path: Path,
                  expected: Optional[int] = None,
                  glob: str = CHUNK_GLOB) -> int:
    """Concatenate chunk tblouts, refusing to merge an incomplete set.

    Every chunk must carry HMMER's terminating `# [ok]`; a task killed by a
    time limit or OOM leaves a valid-looking but truncated file, and
    merging that silently would under-report rescued genes.
    """
    tblout_dir = Path(tblout_dir)
    parts = sorted(tblout_dir.glob(glob))

    if expected is not None and len(parts) != expected:
        raise RuntimeError(
            f"expected {expected} chunk tblouts, found {len(parts)} in "
            f"{tblout_dir} — refusing to merge a partial rescue"
        )
    if not parts:
        raise RuntimeError(f"no chunk tblouts in {tblout_dir}")

    incomplete = [p.name for p in parts
                  if HMMER_OK_MARKER not in p.read_text()[-200:]]
    if incomplete:
        raise RuntimeError(
            f"incomplete hmmsearch chunks (no '{HMMER_OK_MARKER}'): "
            f"{', '.join(incomplete)} — rerun them before merging"
        )

    with open(out_path, "w") as out:
        for p in parts:
            out.write(p.read_text())
    logger.info(f"Merged {len(parts)} chunk tblouts -> {out_path}")
    return len(parts)
